# Polarity language file
# THIS FILE MUST BE MODIFIED MANUALLY, USE VSCODE, VIM, EMACS OR SIMILARS
# Language rules: https://github.com/Aveeryy/Polarity/wiki/Language-rules

language_name = "Español (España)"
language_code = "esES"
language_author = "Aveeryy"

[main]
added_arg = "Añadido argumento \"%s\" de %s"
exit_msg = "Saliendo..."
using_version = "Usando Polarity %s"

[main.arguments.groups]
general = "Opciones generales"
download = "Opciones de descarga"
igloo = "Opciones del iglú"
extractor = "Opciones de %s"
sync = "Opciones de sincronización"
debug = "Opciones de depuración"

[main.arguments.help]
add_to_igloo = "Añade los datos multimedia del enlace al iglú, luego sale"
add_to_sync = "Añade los enlaces a la lista de sincronización, luego sale"
all_extractors = "Muestra información de todos los extractores, luego sale"
debug_directory = "Directorio de depuración personalizado, por defecto usa \"~/.polarity/debug/\""
debug_dump_options = "Escribe un archivo con las opciones en la carpeta de depuración"
debug_print_options = "Muestra las opciones, luego sale"
download_dir_series = "Directorio de descarga para las series"
download_dir_movies = "Directorio de descarga para las películas"
extended_help = "Muestra las opciones de los argumentos"
format_episode = "Formato para el nombre de archivo de los episodios"
format_movie = "Formato para el nombre de archivo de las películas"
format_season = "Formato para el nombre del directorio de las temporadas"
format_series = "Formato para el nombre del directorio de las series"
help = "Muestra la ayuda"
proxy = "Lista de proxies a usar, formato: \"protocolo ip:puerto\""
postprocessing = "Alterna la función de postprocesado de los extractores"
redownload = "Redescarga contenido ya descargado previamente"
resolution = "Resolución de video preferida"
search = "Busca contenido en sitios que tengan compatibilidad"
status_file = "Report download status to file"
sync = ""
sync_refresh = "Intervalo en el que se actualiza la lista de sincronización, en minutos"
update_git = 'Actualiza al último lanzamiento git'
url = "Enlaces introducidos"
verbose = "Nivel de detallado de la salida"

[main.arguments.metavar]
proxy = "<ruta>"
search = "<extractor> <término de búsqueda>"
verbose = "<nivel>"

[polarity]
available_languages = "Idiomas disponibles:"
language_format = "%s (%s) por %s"
no_urls = "Error: no se han introducido enlaces."
use_help = "Usa --ayuda para mostrar todas las opciones disponibles"
use = 'Uso: '

[polarity.exceptions]
verbose_error = "El nivel de detallado debe de ser 1, 2 o 3. Valor actual: %s"

[downloader]
cannot_download_content = "No se puede descargar %s \"%s\": %s"
download_successful = "Se ha descargado %s %s \"%s\""
downloading_content = "Descargando %s \"%s\""
fail_to_delete = "Can't delete old file. you'll need to do it manually"
fail_to_move = "Can't move file to download directory. you'll need to do it manually"
redownload_enabled = "La redescarga está activada, borrando el archivo antiguo..."
no_redownload = "Saltando %s \"%s\". Ya se ha descargado previamente"

[downloader.exceptions]
no_extractor_available = "No hay un extractor para este enlace"

[downloader.media_types]
series = "la serie"
season = "la temporada"
episode = "el episodio"
movie = "la película"

[penguin]
debug_active_threads = "Hilos activos: %d"
debug_already_downloaded = "Saltando el segmento %s, ya ha sido descargado previamente"
debug_downloaded_segment = "Se ha descargado con éxito el segmento %s"
debug_time_download = "La descarga ha tardado: %d segundos"
debug_time_remux = "El multiplexado ha tardado: %d segundos"
thread_converted = "Se ha convertido el hilo \"%s\" a %s"
thread_started = "Se ha iniciado el hilo \"%s\""
threads_started = "Iniciando %d hilos de descarga"

[penguin.arguments]
video_threads = "Hilos de descarga para segmentos de video"
audio_threads = "Hilos de descarga para segmentos de audio"
recovery_threads = "Hilos de descarga para recuperar segmentos perdidos"
segment_timeout = "Tiempo máximo por segmento"

[penguin.protocols.hls]
getting_playlist = "Obteniendo información de la playlist"

[extractor.base]
login_email_prompt = "Email/Usuario: "
login_password_prompt = "Contraseña: "
postprocessing = "Empezando tarea de postprocesado"
postprocessing_empty_path = "La ruta no puede estar vacia"
postprocessing_not_applicable = "No se puede postprocesar este video"
postprocessing_remux = "Remultiplexando el archivo..."

[extractor.base.exceptions]
argument_variable_empty = "El argumento de la variable está vacio"
content_unavailable = "Este contenido no está disponible en tu región o ha sido eliminado de la plataforma"
invalid_type = "Solo puedes crear una temporada en una serie de televisión"
invalid_type_alt = "You can only create an episode in a tv series"
invalid_cloudscraper_method = "'invalid cloudscraper method: \"%s\""
need_to_create_season_01 = "You need to create a season before creating an episode!"
need_to_create_season_02 = "Can't append something that doesn't exist! (create a season first)"
need_to_create_season_03 = "Can't append to something that doesn't exist! (create a season first)"

[extractor.generals]
cloudflare_timeout = "Has hecho demasiadas peticiones a %s."
cloudflare_info = "Todos los episodios descargados serán descargados, ¡prueba dentro de 24 horas para descargar el resto!"
generic_error = "¡Ha ocurrido un error! Mensaje de error: "
get_all_seasons = "Obteniendo información de todas las temporadas"
get_media_info = "Obteniendo información %s \"%s\" (%s)"
login_failure = "Error al iniciar sesión. Motivo del error: %s"
login_loggedas = "Sesión iniciada como %s"
login_success = "Inicio de sesión exitoso"
obtained_media_id = "Obtenido id de %s: %s"
skip_episode_id = "Saltando el episodio con id %s, %s"
skip_episode_name = "Saltando el episodio \"%s\", %s"

[extractor.generals.exceptions]
cannot_identify_url = "No se ha podido identificar el enlace"

[extractor.generals.media_types]
series = "de la serie"
season = "de la temporada"
episode = "del episodio"
movie = "de la película"

[update]
downloading_git = "Descargando el último lanzamiento git"
downloading_release = "Descargando el último lanzamiento estable"
downloading_native = "Descargando el último binario nativo"
installing_to_path = "Instalando en %s"
successful_install = "¡Instalación exitosa! Saliendo en %d segundos"
updating = 'Actualizando...'

[update.exceptions]
unsupported_native = "Actualizar binarios nativos no está implementado"

[atresplayer]
no_content_in_season = "No hay episodios en %s (%s)"

[atresplayer.exceptions]
invalid_codec = "El códec especificado en los ajustes es inválido."

[atresplayer.arguments]
# TODO

[crunchyroll]
content_unavailable = "No se han encontrado temporadas, ¡este contenido no está disponible en tu región!"
fail_to_download_reason_01 = "El contenido requiere una cuenta premium (o ha ocurrido un error)"
invalid_metadata = "Código de idioma de metadatos inválido. cambiando al ajuste predeterminado"
session_id = "ID de sesión: "
session_id_custom = "Usando id de sesión personalizado: %s"
session_id_failure = "Ha ocurrido un error al intentar obtener el id de sesión, reintentando..."
session_id_forced = "Forzando nuevo id de sesión"
session_id_local = "Usando id de sesión local"
session_id_region = "Obteniendo id de sesión de tu región"
session_id_usa = "Obteniendo id de sesión estadounidense"
unavailable_episode_reason = "Requiere una cuenta premium o no está disponible en tu región"

[crunchyroll.arguments]
# TODO