# Polarity language file
# THIS FILE MUST BE MODIFIED MANUALLY, USE VSCODE, VIM, EMACS OR SIMILARS
# Language rules: https://github.com/Aveeryy/Polarity/wiki/Language-rules

name = "Español (España)"
code = "esES"
author = "Aveeryy"

[main]
exit_msg = "Saliendo..."

[args]
added_arg = "Añadido argumento \"%s\" de %s"

[args.groups]
general = "Opciones generales"
download = "Opciones de descarga"
extractor = "Opciones de %s"
sync = "Opciones de sincronización"
debug = "Opciones de depuración"

[args.help]
accounts_dir = "Directorio alternativo para archivos de cuentas"
binaries_dir = "Directorio alternativo para binarios de ffmpeg"
config_file = "Dirección alternativa para el archivo de configuración"
download_dir_series = "Directorio de descarga para las series"
download_dir_movies = "Directorio de descarga para las películas"
dump = "Volcar información a un archivo"
email = "Email de la cuenta de %s"
exit_after_dump = "Salir tras volcar la información"
extended_help = "Muestra las opciones de los argumentos"
format_episode = "Formato para el nombre de archivo de los episodios"
format_movie = "Formato para el nombre de archivo de las películas"
format_season = "Formato para el directorio de las temporadas"
format_series = "Formato para el directorio de las series"
format_search = "Formato para los resultados de búsqueda"
help = "Muestra la ayuda"
install_languages = "Instala los idiomas especificados"
installed_languages = "Muestra una lista de los idiomas instalados"
language = "Utiliza el idioma especificado"
language_dir = "Directorio alternativo para archivos de idioma"
log_dir = "Directorio alternativo para archivos de registro"
log_file = "Dirección alternativa para el registro de descargas"
max_results = "Máximo absoluto de resultados de búsqueda"
max_results_per_extractor = "Resultados de búsqueda por extractor"
max_results_per_type = "Resultados de búsqueda por tipo de contenido"
mode = "Modo de ejecución"
pass = "Contraseña de la cuenta de %s"
redownload = "Permite descargar contenido ya descargado previamente"
resolution = "Resolución de video preferida"
results_trim = "Reduce los nombres de los resultados de búsqueda"
update = "Actualiza al último lanzamiento estable"
update_git = 'Actualiza al último lanzamiento git'
update_languages = "Actualiza los idiomas descargados"
url = "Enlaces"
verbose = "Nivel de detallado de la salida"
verbose_log = "Nivel de detallado de los registros"

[args.metavar]
proxy = "<ruta>"
search = "<término de búsqueda>"
verbose = "<nivel>"

[polarity]
all_tasks_finished = "Todas las tareas han finalizado"
available_languages = "Idiomas disponibles:"
changed_index = "Cambiado índice a: %s"
config_path = "Archivo de configuración: %s"
created_filter = "Creado objeto %s con los parámetros %s y el filtro %s"
deleting_log = "Nada que hacer, borrando registro"
dump_options = "opciones"
dumped_to = "Volcadas %s en: %s"
language_format = "%s [%s] por %s"
log_path = "Escribiendo registro en: %s"
not_a_content_id = '"%s" no es un identificador de contenido'
no_space_left = "No queda espacio disponible en el dispositivo, saliendo..."
python_version = "Python %s | %s"
requesting = "Solicitando: %s"
search_no_results = "No se han encontrado resultados con el término: %s"
search_term = "Término de búsqueda: "
usage = "polarity [OPCIONES] URL [URL...]"
use_help = "Usa --help para mostrar todas las opciones disponibles"
use = 'Uso: '
unsupported_python = "Versión de Python no soportada (%s), actualiza a Python 3.7 o superior"
update_available = "La versión %s está disponible"
using_version = "Polarity %s"

[polarity.except]
invalid_http_method = "Método HTTP inválido: %s"
missing_ffmpeg = "ffmpeg no está instalado o no está en PATH"
verbose_error = "Nivel de detallado invalido: %s"
verbose_log_error = "Nivel de detallado de registros invalido: %s"

[singularity]
extracting_keys = "Extrayendo llaves de Widevine"
using_version = "Usando Singularity %s"

[dl]
cannot_download_content = "No se puede descargar %s \"%s\": %s"
download_id = "el id de descarga"
download_successful = "Se ha descargado %s \"%s\""
downloading_content = "Descargando %s \"%s\""
redownload_enabled = "La redescarga está activada, borrando el archivo antiguo..."
no_extractor = "Saltando %s \"%s\". No hay un extractor compatible"
no_redownload = "Saltando %s \"%s\". Ya se ha descargado previamente"
url = "la URL"

[penguin]
assisting = "Asistiendo al hilo %s con %s"
doing_binary_concat = "Realizando unión de segmentos binaria en la pista %s de %s"
doing_decryption = "Desencriptando la pista %s de %s con la llave %s"
debug_already_downloaded = "Saltando el segmento %s, ya se ha descargado previamente"
debug_time_download = "La descarga ha tardado: %d segundos"
debug_time_remux = "El multiplexado ha tardado: %d segundos"
incompatible_stream = "Stream no compatible: %s"
key_download = "Descargando la llave del segmento %s"
output_file_broken = "No se ha podido cargar el archivo de datos de salida, recreando..."
processing_stream = "Procesando el stream %s"
resume_file_backup_broken = "No se ha podido cargar la copia del archivo de datos de continuación, recreando"
resume_file_broken = "No se ha podido cargar el archivo de datos de continuación, usando la copia"
resume_file_recreation = "Recreando los datos de continuación..."
resuming = "Resumiendo la descarga de %s..."
segment_downloaded = "Se ha descargado con éxito el segmento %s"
segment_retry = "La descarga del segmento %s ha fallado, reintentando..."
thread_started = "Se ha iniciado el descargador \"%s\""
threads_started = "Iniciando %d descargadores de segmentos"

[penguin.args]
ffmpeg_codec = "Ajustes de codificación del postprocesado"
retries = "Número de reintentos para descargar un segmento"
segment_downloaders = "Número de descargadores de segmentos"

[penguin.protocols]
getting_playlist = "Analizando playlist"
getting_stream = "Analizando stream"
multiple_video_bitrates = "Múltiples pistas de audio con la misma resolución detectadas"
picking_best_stream_0 = "Seleccionando el stream de video con mayor resolución"
picking_best_stream_1 = "Seleccionando el stream de video con mayor bitrate"
picking_best_stream_2 = "Seleccionando el stream de audio con mayor bitrate"
selected_stream = "Stream seleccionado: %s"

[extractor.base]
login_email_prompt = "Email/Usuario: "
login_password_prompt = "Contraseña: "

[extractor.base.except]
argument_variable_empty = "El argumento de la variable está vacio"
content_unavailable = "Este contenido no está disponible en tu región o ha sido eliminado de la plataforma"
invalid_type_season = "Solo puedes crear una temporada en una serie de televisión"
invalid_type_episode = "Solo puedes crear un episodio con una serie o un podcast"
need_to_create_season = "Tienes que crear una temporada antes de crear un episodio o usar el parámetro \"independent\""

[extractor]
cloudflare_timeout = "Has hecho demasiadas peticiones a %s."
cloudflare_info = "Todos los episodios procesados serán descargados, ¡prueba dentro de 24 horas para descargar el resto!"
generic_error = "¡Ha ocurrido un error! Mensaje de error: "
get_all_seasons = "Obteniendo información de todas las temporadas"
get_media_info = "Obteniendo información %s \"%s\" (%s)"
login_failure = "Error al iniciar sesión. Error: %s"
login_loggedas = "Sesión iniciada como %s"
login_success = "Inicio de sesión exitoso"
search_no_results = "No ha habido resultados en la categoría %s con el término %s"
skip_episode_id = "Saltando el episodio con identificador %s, %s"
skip_episode_name = "Saltando el episodio \"%s\", %s"
waiting_for_login = "Esperando a que inicies sesión"

[extractor.generals.except]
cannot_identify_url = "No se ha podido identificar el enlace"

[types]
series = "la serie"
season = "la temporada"
episode = "el episodio"
movie = "la película"

[types.alt]
series = "de la serie"
season = "de la temporada"
episode = "del episodio"
movie = "de la película"

[update]
downloading_git = "Descargando el último lanzamiento git"
downloading_release = "Descargando el último lanzamiento estable"
downloading_native = "Descargando el último binario nativo"
installing_to_path = "Instalando en %s"
successful_install = "¡Instalación exitosa! Saliendo en %d segundos"
updating = 'Actualizando...'

[update.except]
unsupported_native = "Actualizar binarios nativos no está implementado"

[atresplayer]
no_content_in_season = "No hay episodios en %s (%s)"

[atresplayer.except]
invalid_codec = "El códec especificado en los ajustes es inválido."

[atresplayer.args]
codec = "Preferencia del códec"

[crunchyroll]
alt_bearer_fail = "La obtención del token Bearer alternativa ha fallado, reintentando con el servidor principal"
alt_bearer_no_server = "No se ha especificado un servidor de token Bearer alternativo, cambiando al principal"
alt_bearer_success = "Se ha obtenido con éxito el token Bearer del servidor alternativo"
getting_bearer = "Obteniendo token Bearer"
getting_cms = "Obteniendo políticas CMS"
getting_cms_fail = "Ha fallado la obtención de políticas CMS"
using_method = "Usando el método \"%s\""

[crunchyroll.args]
subs = "Idiomas de los subtítulos a descargar"
dubs = "Idiomas de los doblajes a descargar"
meta = "Idioma de los metadatos"
hard = "Descarga una versión \"hardsub\""
